/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package e01.solution;

import org.junit.Test;

import e01.solution.TwoNumberSum;

import static org.junit.Assert.*;

public class TwoNumberSumTest {
    @Test public void testSomeLibraryMethod() {
        TwoNumberSum classUnderTest = new TwoNumberSum();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
