/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mak' at '31/5/17 4:25 PM' with Gradle 2.14.1
 *
 * @author mak, @date 31/5/17 4:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
